[package]
name = "elusiv"
version = "0.1.0"
edition = "2021"

[features]
# Adds the functions `instruction_name(..) -> solana_program::instruction::Instruction` to `ElusivInstruction`
instruction-abi = []
# Switches to a compute units per tx model
tx-wide-compute-cap = []

[dependencies]
elusiv-macros = { path = "elusiv-macros" }
elusiv-interpreter = { path = "elusiv-interpreter" }

solana-program = "1.9.5"
ark-bn254 = "0.3.0"
ark-ff = "0.3.0"
ark-ec = "0.3.0"

[dev-dependencies]
elusiv = { path = ".", features = ["instruction-abi"] }
assert_matches = "1.5.0"
solana-program-test = "1.9.5"
solana-sdk = "1.9.5"
ark-groth16 = { version = "0.3.0", default-features = false }

[lib]
name = "elusiv"
crate-type = ["cdylib", "lib"]