[package]
name = "elusiv"
version = "0.1.0"
edition = "2021"

[features]
test-bpf = []

[dependencies]
# Solana program
solana-program = "1.9.5"
# Groth16 verification
ark-bn254 = "0.3.0"
ark-ff = "0.3.0"
ark-ec = "0.3.0"
byteorder = "1.4.3"

[dev-dependencies]
assert_matches = "1.5.0"
solana-program-test = "1.9.5"
solana-sdk = "1.9.5"
solana-validator = "1.9.5"
rand = "0.8.4"
base64 = "0.13.0"
num-bigint = "0.4.3"
num-traits = "0.2.14"
ark-groth16 = { version = "0.3.0", default-features = false }
env_logger = "0.9.0"
log = "0.4.14"

[lib]
name = "elusiv"
crate-type = ["cdylib", "lib"]