[package]
name = "elusiv"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.9.2"

[dev-dependencies]
assert_matches = "1.4.0"
solana-program-test = "1.9.2"
solana-sdk = "1.9.2"
solana-validator = "1.9.2"

[lib]
name = "elusiv"
crate-type = ["cdylib", "lib"]