[package]
name = "elusiv"
version = "0.1.0"
edition = "2021"
publish = false

[features]
# Adds the functions `instruction_name(..) -> solana_program::instruction::Instruction` to `ElusivInstruction`
instruction-abi = []

[dependencies]
elusiv-interpreter = { path = "./elusiv-interpreter" }
elusiv-macros = { path = "./elusiv-macros" }

solana-program = "1.9.5"
borsh = { version = "0.9.3", features = ["const-generics"] }
ark-bn254 = "0.3.0"
ark-ff = "0.3.0"
ark-ec = "0.3.0"

[dev-dependencies]
rand = "0.8.5"
elusiv = { path = ".", features = ["instruction-abi"] }
assert_matches = "1.5.0"
solana-program-test = "1.9.5"
solana-sdk = "1.9.5"
ark-groth16 = { version = "0.3.0", default-features = false }

[lib]
name = "elusiv"
crate-type = ["cdylib", "lib"]