[[program_id]]
name = "elusiv"
mainnet = "AQJN5bDobGyooyURYGfhFCWK6pfEdEf17gLxixEvY6y7"
devnet = "HSwKaCUZPTQXsrrgV1KYUvF5yn9RHg86jEtRViTE5fUV"
local = "C5F74e1ECSxNHY1i4ZJ5SS7d55cNezfa9ccvojrHi6Yd" # Local testing keypair BIP39 seed: chronic river provide glue citizen hybrid omit siege fan crime match ball

[[program_id]]
name = "elusiv-warden-network"
mainnet = "AQJN5bDobGyooyURYGfhFCWK6pfEdEf17gLxixEvY6y7"
devnet = "G1C8kQKEwR2snboP7JBTNq9fm3V2wW7VLizawvmGZ6gp"
local = "B6ZffajG1Jc5LSq76HAXNbJG7drLdRtCFG7DcBND9Lfb" # Local testing keypair BIP39 seed: riot wire enrich solution alien shift wool bulb trophy matter stay sponsor