[program_id]
mainnet = "AQJN5bDobGyooyURYGfhFCWK6pfEdEf17gLxixEvY6y7"
devnet = "HSwKaCUZPTQXsrrgV1KYUvF5yn9RHg86jEtRViTE5fUV"

# For local testing you can generate the local test keypair with this BIP39 seed:
# chronic river provide glue citizen hybrid omit siege fan crime match ball
local = "C5F74e1ECSxNHY1i4ZJ5SS7d55cNezfa9ccvojrHi6Yd"