[package]
name = "elusiv-macro-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
elusiv-interpreter = { path = "../elusiv-interpreter" }
ark-bn254 = "0.3.0"
ark-ff = "0.3.0"
ark-ec = "0.3.0"
solana-program = "1.10.13"