[package]
name = "elusiv-types"
version = "0.1.0"
edition = "2021"
publish = false

[features]
instruction-abi = []

[dependencies]
elusiv-derive = { path = "./../elusiv-derive" }
solana-program = "=1.10.39"
borsh = { version = "=0.9.3", features = ["const-generics"] }