name: Cargo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - setup:
      run: sh -c "$(curl -sSfL https://release.solana.com/v1.9.6/install)"
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose