name: verifying-key check

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://${{ secrets.GH_SECRET }}@github.com/".insteadOf
          https://github.com/
      - name: Fetch and compare vkeys
        run: |
          sh ./vkey.sh send_quadra temp2/send_quadra
          if diff -rq temp2/send_quadra/send_quadra elusiv/src/proof/vkeys/send_quadra ; then
            echo "Vkeys up to date"
          else
            echo "Vkeys not up to date"
            exit 1
          fi
